### ISSUE TITLE
Setting up CI/CD for testing the assistant

### ISSUE THREAD

**Issue by cdhiraj40** [enviroCar/envirocar-rasa-bot#3]
## Description

Even though developing a contextual assistant is different from developing traditional software, we should still follow software development best practices. Setting up a Continuous Integration (CI) and Continuous Deployment (CD) pipeline will ensure that every commit/PR is not introducing new problems or negatively impacting the performance of our assistant.

## Solution

We can use **[GitHub Actions](https://github.com/features/actions)** to run CI checks on every PR or commit. This action will train, test, and publish a summary.

**Comment by devAyushDubey** [comment]
## Implement [Rasa-Train-Test-Github-Action (RTTG)](https://github.com/RasaHQ/rasa-train-test-gha) in a primary testing workflow

## Describe:
Aim is to develop a CI Pipeline for testing the effects of code changes in Pull Requests (PRs) on the accuracy and performance of the rasa model and API, while also providing a comprehensive report on the result of the test. A testing step would inherently require a build (train) step.

## Solution:
Using the [Rasa-Train-Test-Github-Action (RTTG)](https://github.com/RasaHQ/rasa-train-test-gha) as a part of our primary test workflow we can achieve the above goal.

## Test Report Features:
- [ ] Test Reports in PR Comments
- [ ] Test Reports Storage in a Directory (for reference)

I will be creating two separate PRs each implementing one of the test report feature.

**Comment by devAyushDubey** [comment]
Hey @cdhiraj40 could you please assign the issue to me and also add the labels. Thanks 😀
